In [2]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


### Loading the popular Iris dataset 

In [45]:
data = iris

### Insatlling and loading the required package for estimating the Naive Bayes Model

In [7]:
install.packages('klaR')

also installing the dependencies 'R.methodsS3', 'R.oo', 'R.utils', 'R.cache', 'styler', 'classInt', 'labelled', 'combinat', 'questionr'




package 'R.methodsS3' successfully unpacked and MD5 sums checked
package 'R.oo' successfully unpacked and MD5 sums checked
package 'R.utils' successfully unpacked and MD5 sums checked
package 'R.cache' successfully unpacked and MD5 sums checked
package 'styler' successfully unpacked and MD5 sums checked
package 'classInt' successfully unpacked and MD5 sums checked
package 'labelled' successfully unpacked and MD5 sums checked
package 'combinat' successfully unpacked and MD5 sums checked
package 'questionr' successfully unpacked and MD5 sums checked
package 'klaR' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\acer\AppData\Local\Temp\Rtmp4QPdCi\downloaded_packages


In [8]:
library(klaR)

Warning message:
"package 'klaR' was built under R version 4.3.1"
Loading required package: MASS



In [46]:
data <- data[1:149,]

### Instantiating and Fitting the Naive Bayes Model 

In [47]:
model <- NaiveBayes(Species~.,data=data)

### Extracting Conditional Probabilities

In [48]:
model$tables

$Sepal.Length
               [,1]      [,2]
setosa     5.006000 0.3524897
versicolor 5.936000 0.5161711
virginica  6.602041 0.6345897

$Sepal.Width
               [,1]      [,2]
setosa     3.428000 0.3790644
versicolor 2.770000 0.3137983
virginica  2.973469 0.3258166

$Petal.Length
               [,1]      [,2]
setosa     1.462000 0.1736640
versicolor 4.260000 0.4699110
virginica  5.561224 0.5537058

$Petal.Width
               [,1]      [,2]
setosa     0.246000 0.1053856
versicolor 1.326000 0.1977527
virginica  2.030612 0.2755329

### Testing Fitted Model on a new observation

In [51]:
x <- data[150,-5]
predict(model,x)

$class
    NA 
setosa 
Levels: setosa versicolor virginica

$posterior
      setosa versicolor virginica
NA 0.3355705  0.3355705 0.3288591